---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

branches:
  except:
  - master

install:
  # Install requirements
  - pip install -r requirements.txt

before_script: cd tests
script:
  - git clone https://github.com/termlen0/demo provisioner

  - |
    ansible-playbook provisioner/provision.yaml \
    -e env="${TRAVIS_BRANCH}" \
    -e chg_num="${TRAVIS_PULL_REQUEST_BRANCH}" \
    -e user_id="${TRAVIS_PULL_REQUEST}"

  - sed -i -e "s/DEMO-PROD/${TRAVIS_PULL_REQUEST_BRANCH}\-${TRAVIS_PULL_REQUEST}/" test-inventory/ec2.ini

  - ansible-playbook -i test-inventory ../deploy.yaml

  - |
    ansible-playbook -i inventory main.yaml \
      -e env="${TRAVIS_BRANCH}" \
      -e chg_num="${TRAVIS_PULL_REQUEST_BRANCH}" \
      -e user_id="${TRAVIS_PULL_REQUEST}" \
      -e pipeline="${TRAVIS_BRANCH}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
