---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  # Install tower-cli
  - pip install ansible-tower-cli
  # Check ansible version
  - ansible --version
  # Check tower-cli version
  - tower-cli --version

before_script: cd tests
script:
  - |
    ansible-playbook -i inventory main.yaml \
      -e env="${TRAVIS_BRANCH}" \
      -e chg_num="${TRAVIS_PULL_REQUEST_BRANCH}" \
      -e user_id="${TRAVIS_PULL_REQUEST}" \
      -e pipeline="${TRAVIS_BRANCH}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
