branches:
  only:
  - add_provisioning
services: docker
env:
  matrix:
  - distro: centos7
  global:
  - secure: AUVzahm3YEW6B+b4+U6c2GfuZIxUzw0YjlCICLFtZQZoppMxTL/7fzULvzO93rM9LU5dUaN5uZAzotzdHonC++V4DJqPymiAXyskr8VjwJp8WPw2KHXo51jolOOikIuslRxOrn7DjRxMjF2FLWczuaC+TgTQZc0wX1HUhEtAuPpUe4cOmnU8dwH0Cd+z61AiL/uzuIDAiBHo6svRpHNqcTyv41rHH1El9K/2/cISUjR/lFyQ0IN0D0W7fNHwOYNF1VYbGVoyvfWMBtpScqgMu6WLyh+mvdlJyP86mSwm6hZpKXqAOW2AcpKnwidLx6TZceQQ+WM0Fzt673e5KnrPJSnrsYPgv3G/Qf9C0mhK/TvKUJdJOtp3u9yTIAkRrgnAhel+gf6t0YZ6rGplt2sKij5o/SjOTnFghEEnJ9HQlqogxvCVFXmE+hakAM98xQ93UHYY00J+NrPLlE9Kls7StaXManHGUIObesHNdZwbqP8NaRRGex0u8o5js8gKRVFcm88GBZY5juEwQdJ65CbOuldQMcgxxuOjjTJwbWeFusuGwKxC0Px3eUENMs1c9XmclBW5FZghez1O/7eXesLb1uP8qg/IbTR/Cxqct1i1P3uFZI0MXUw400Wl4cQslwFD39ijM7q7efUrr1an4TB0+p6nKhe0uVfkEqzABJ+LPsw=
  - secure: oyYTm5mUJ5oW85X9gYngvEFDemwLjNp3lQyKUe2Oi5kA38Q91qCPAJS/wFB61Yf4L6MRe1q7G8SBFUrppmqwsmi6OjsrGnXhbm48NxZMmt7mAAQiLw3qstezs7SJEnwPAQZiKoRRo1Bad76RNTisijF0+2n6d05M9Jb3cefrM0zToT1lVeeOCPT6SJnX/12qnrR6SekqunkvpQYm829ua93kOZfD3+iFQy0w4IJ6sCauOErhGfdZUhxtiY/bLPDl66ICAze68Ne1BfDrD8QVS3Tu4inVh4hriifvmR8WB6ShLtGnEkpKYhSkODPJpc0txy+McugjE8r6jJ4Y7uisdcWDcTZlq2LOHm0GVC9wueMX7qLM5WJmz8M2UL3ai9AszWBuIphhomjrhIm7z5Wt7RCuOfnjwszNUGYMFT7Jr05fiYmeiDLotdZkM1bFyAVvVdys91Hyv8hFVUMYifYarxwbLefzetrZ8WojT+pslpbwzwJFfs5lMBvUH8MtvmlSfYc1PZDL2+4eDqGhT4ajg6yXjeFml2K1UScaK1uWEQCdlj62O8slqrzBgtUkRIYnvPF57XFh51Mn5WSGYzw6GKhhgLYyaUfcb4S0fuwBOnWnZQvWLAj+16cytszf9IRZw4ZdbQnxgXrl3oqXcNtQyneXX49BuDod1OWNKi8v4oI=
before_install:
  - echo $ANSIBLE_VAULT_PASSWORD
script:
- export container_id=$(date +%s)
- export cleanup=false
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/termlen0/2e05b0682a31aab73a77effe26ea2ee8/raw
- chmod +x ${PWD}/tests/test.sh
- "${PWD}/tests/test.sh"
