---
- name: "Launch pipeline"
  docker_container:
    env: "{{ do_pipeline_env }}"
    name: "{{ do_pipeline_name }}-{{ lookup('pipe','date +%Y%d%m%H%M%s') }}"
    image: "{{ do_pipeline_image }}"
    privileged: "{{ do_pipeline_privileged }}"
    init: "{{ do_pipeline_init }}"
    command:
      - ansible-playbook -v -c local /data/pipelines/{{ do_pipeline_name }}/main.yaml
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - {{ do_pipeline_data_path }}:/data:ro
      - {{ do_pipeline_data_path }}/test/roles:/etc/ansible/roles:ro
