all:
  hosts:
    localhost:
    site1_remote1:
    site1_core1:
    site2_remote2:
    site2_core2:
  children:
    site1:
      children:
        tag_location_site1:
    tag_location_site1:
    site2:
      children:
        tag_location_site2:
    tag_location_site2:
