- name: Install Docker packages
  package:
    name:
      - docker
      - device-mapper-libs
      - device-mapper-event-libs
    state: "present"

- name: "pip install docker"
  pip:
    name: docker
    state: present

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: "running"
    enabled: "yes"

- name: Ensure awx is member of docker group
  user:
    name: "awx"
    groups: docker
    append: yes
