---
dependencies:
  - ansible

galaxy_info:
  role_name: ansible_review
  author: "Victor da Costa (@victorock)"
  description: "Ansible: ansible-review"
  company: "Ansible"
  license: GPLv3
  min_ansible_version: 2.6
  platforms: []
  galaxy_tags: []
