---
- name: Run ansible-lint on yaml files
  shell: >
    find * -name "*.yml" -or -name "*.yaml" |
        xargs --no-run-if-empty ansible-lint -p --nocolor
  args:
    chdir: "{{ do_ansible_lint_folder }}"
